console.log(1)
const p = new Promise((resolve, reject) => {
    console.log(2)
    resolve(6)
    //reject(6)
    console.log(3)
})
console.log(4)
//p.then(value => console.log('resolve', value), reason => console.log('reject', reason))
//p.then(value => console.log('resolve', value))
//p.then(null, reason => console.log('reject', reason))
//p.then(value => {throw new Error(value)})
p.then(value => {throw value})
 .then(value => console.log('resolve', value))
 .catch(reason => console.log('reject', reason))
console.log(5)
